### ISSUE TITLE
Codigo duplicado.

### ISSUE THREAD

**Issue by enmanuel97** [opticrd/do-fuels-api#1]
El codigo del combustible esta duplicado. El codigo esta asignado a dos tipos de combustible.
![image](https://user-images.githubusercontent.com/22060566/132901994-bb2cc0da-5494-468d-8fa3-4bbab760d911.png)

**Comment by gustavovalverde** [comment]
Hola Enmanuel; sí. Estos código del Gasoil Premium y el Gasoil Óptimo son de los códigos Platts: https://www.spglobal.com/platts/PlattsContent/_assets/_files/en/our-methodology/methodology-specifications/americas-refined-oil-products-methodology.pdf 

No identificamos que haya una diferencia entre uno y otro. Incluso en el histórico hay un punto donde deja de utilizarse un nombre y pasa al otro. Por eso ves que en el ejemplo que envías el Gasoil Premium no tiene precio y el óptimo sí.

**Comment by enmanuel97** [comment]
Ok ya entiendo, gracias por su pronta respuesta :D
PD: Muy buen trabajo el que estan haciendo 👍 esperando colaborar con este proyecto
