### ISSUE TITLE
Data desactualizada

### ISSUE THREAD

**Issue by setejera** [opticrd/do-fuels-api#2]
Buenas tardes,

Estaba revisando la data de este API de manera exploratoria para un proyecto, ingrese los parametros para recibir una respuesta con la informacion mas actualizada de los precios de gasolina premium y la ultima fecha en la respuesta fue del 11 de Diciembre 2021. 

![image](https://user-images.githubusercontent.com/45438505/152654941-de8c61f1-22b3-4bcb-9f84-7a4f532ba2fa.png)

![image](https://user-images.githubusercontent.com/45438505/152654954-d70c2819-6fb4-45e5-a3dd-79662bc3b72a.png)

Notificando en caso de que no estaban al tanto.

Slds cordiales,
Sebastian

**Comment by marluanespiritusanto** [comment]
Saludos @setejera,

En efecto, la data está desactualizada debido a que la fuente de datos que suplía nuestra base de datos (RSS del [MICM](https://www.micm.gob.do)) ha sido removida.

Justo ahora nuestro equipo está trabajando en una alternativa para restituir el servicio nuevamente.

Cerraré este issue y nos comunicaremos nuevamente cuando el problema esté resuelto.
